name: python-code-linter

on: push

jobs:
  python-linting-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Super-Linter
        uses: super-linter/super-linter@v7.1.0
        env:
          DEFAULT_BRANCH: main  # Adjust if your default branch is different
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
  
